export default [
    {
      "login": "Ugochrist13",
      "id": 50428682,
      "node_id": "MDQ6VXNlcjUwNDI4Njgy",
      "avatar_url": "https://avatars.githubusercontent.com/u/50428682?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ugochrist13",
      "html_url": "https://github.com/Ugochrist13",
      "followers_url": "https://api.github.com/users/Ugochrist13/followers",
      "following_url": "https://api.github.com/users/Ugochrist13/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ugochrist13/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ugochrist13/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ugochrist13/subscriptions",
      "organizations_url": "https://api.github.com/users/Ugochrist13/orgs",
      "repos_url": "https://api.github.com/users/Ugochrist13/repos",
      "events_url": "https://api.github.com/users/Ugochrist13/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ugochrist13/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "codewithemmy",
      "id": 58103602,
      "node_id": "MDQ6VXNlcjU4MTAzNjAy",
      "avatar_url": "https://avatars.githubusercontent.com/u/58103602?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/codewithemmy",
      "html_url": "https://github.com/codewithemmy",
      "followers_url": "https://api.github.com/users/codewithemmy/followers",
      "following_url": "https://api.github.com/users/codewithemmy/following{/other_user}",
      "gists_url": "https://api.github.com/users/codewithemmy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/codewithemmy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/codewithemmy/subscriptions",
      "organizations_url": "https://api.github.com/users/codewithemmy/orgs",
      "repos_url": "https://api.github.com/users/codewithemmy/repos",
      "events_url": "https://api.github.com/users/codewithemmy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/codewithemmy/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Adesina-Abiodun",
      "id": 101020483,
      "node_id": "U_kgDOBgVzQw",
      "avatar_url": "https://avatars.githubusercontent.com/u/101020483?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Adesina-Abiodun",
      "html_url": "https://github.com/Adesina-Abiodun",
      "followers_url": "https://api.github.com/users/Adesina-Abiodun/followers",
      "following_url": "https://api.github.com/users/Adesina-Abiodun/following{/other_user}",
      "gists_url": "https://api.github.com/users/Adesina-Abiodun/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Adesina-Abiodun/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Adesina-Abiodun/subscriptions",
      "organizations_url": "https://api.github.com/users/Adesina-Abiodun/orgs",
      "repos_url": "https://api.github.com/users/Adesina-Abiodun/repos",
      "events_url": "https://api.github.com/users/Adesina-Abiodun/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Adesina-Abiodun/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "just-Muzz",
      "id": 102549811,
      "node_id": "U_kgDOBhzJMw",
      "avatar_url": "https://avatars.githubusercontent.com/u/102549811?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/just-Muzz",
      "html_url": "https://github.com/just-Muzz",
      "followers_url": "https://api.github.com/users/just-Muzz/followers",
      "following_url": "https://api.github.com/users/just-Muzz/following{/other_user}",
      "gists_url": "https://api.github.com/users/just-Muzz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/just-Muzz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/just-Muzz/subscriptions",
      "organizations_url": "https://api.github.com/users/just-Muzz/orgs",
      "repos_url": "https://api.github.com/users/just-Muzz/repos",
      "events_url": "https://api.github.com/users/just-Muzz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/just-Muzz/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "ItsTemi",
      "id": 104791178,
      "node_id": "U_kgDOBj78ig",
      "avatar_url": "https://avatars.githubusercontent.com/u/104791178?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ItsTemi",
      "html_url": "https://github.com/ItsTemi",
      "followers_url": "https://api.github.com/users/ItsTemi/followers",
      "following_url": "https://api.github.com/users/ItsTemi/following{/other_user}",
      "gists_url": "https://api.github.com/users/ItsTemi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ItsTemi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ItsTemi/subscriptions",
      "organizations_url": "https://api.github.com/users/ItsTemi/orgs",
      "repos_url": "https://api.github.com/users/ItsTemi/repos",
      "events_url": "https://api.github.com/users/ItsTemi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ItsTemi/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Coolestboy01",
      "id": 104928410,
      "node_id": "U_kgDOBkEUmg",
      "avatar_url": "https://avatars.githubusercontent.com/u/104928410?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Coolestboy01",
      "html_url": "https://github.com/Coolestboy01",
      "followers_url": "https://api.github.com/users/Coolestboy01/followers",
      "following_url": "https://api.github.com/users/Coolestboy01/following{/other_user}",
      "gists_url": "https://api.github.com/users/Coolestboy01/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Coolestboy01/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Coolestboy01/subscriptions",
      "organizations_url": "https://api.github.com/users/Coolestboy01/orgs",
      "repos_url": "https://api.github.com/users/Coolestboy01/repos",
      "events_url": "https://api.github.com/users/Coolestboy01/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Coolestboy01/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Adebayotobi",
      "id": 105372829,
      "node_id": "U_kgDOBkfcnQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/105372829?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Adebayotobi",
      "html_url": "https://github.com/Adebayotobi",
      "followers_url": "https://api.github.com/users/Adebayotobi/followers",
      "following_url": "https://api.github.com/users/Adebayotobi/following{/other_user}",
      "gists_url": "https://api.github.com/users/Adebayotobi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Adebayotobi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Adebayotobi/subscriptions",
      "organizations_url": "https://api.github.com/users/Adebayotobi/orgs",
      "repos_url": "https://api.github.com/users/Adebayotobi/repos",
      "events_url": "https://api.github.com/users/Adebayotobi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Adebayotobi/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Praise-QueenEsther",
      "id": 109555214,
      "node_id": "U_kgDOBoeuDg",
      "avatar_url": "https://avatars.githubusercontent.com/u/109555214?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Praise-QueenEsther",
      "html_url": "https://github.com/Praise-QueenEsther",
      "followers_url": "https://api.github.com/users/Praise-QueenEsther/followers",
      "following_url": "https://api.github.com/users/Praise-QueenEsther/following{/other_user}",
      "gists_url": "https://api.github.com/users/Praise-QueenEsther/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Praise-QueenEsther/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Praise-QueenEsther/subscriptions",
      "organizations_url": "https://api.github.com/users/Praise-QueenEsther/orgs",
      "repos_url": "https://api.github.com/users/Praise-QueenEsther/repos",
      "events_url": "https://api.github.com/users/Praise-QueenEsther/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Praise-QueenEsther/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "topeisah",
      "id": 110097953,
      "node_id": "U_kgDOBo_2IQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/110097953?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/topeisah",
      "html_url": "https://github.com/topeisah",
      "followers_url": "https://api.github.com/users/topeisah/followers",
      "following_url": "https://api.github.com/users/topeisah/following{/other_user}",
      "gists_url": "https://api.github.com/users/topeisah/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/topeisah/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/topeisah/subscriptions",
      "organizations_url": "https://api.github.com/users/topeisah/orgs",
      "repos_url": "https://api.github.com/users/topeisah/repos",
      "events_url": "https://api.github.com/users/topeisah/events{/privacy}",
      "received_events_url": "https://api.github.com/users/topeisah/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "ozavizcodes",
      "id": 110241515,
      "node_id": "U_kgDOBpIm6w",
      "avatar_url": "https://avatars.githubusercontent.com/u/110241515?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ozavizcodes",
      "html_url": "https://github.com/ozavizcodes",
      "followers_url": "https://api.github.com/users/ozavizcodes/followers",
      "following_url": "https://api.github.com/users/ozavizcodes/following{/other_user}",
      "gists_url": "https://api.github.com/users/ozavizcodes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ozavizcodes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ozavizcodes/subscriptions",
      "organizations_url": "https://api.github.com/users/ozavizcodes/orgs",
      "repos_url": "https://api.github.com/users/ozavizcodes/repos",
      "events_url": "https://api.github.com/users/ozavizcodes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ozavizcodes/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Joshua-Mondie",
      "id": 110495988,
      "node_id": "U_kgDOBpYI9A",
      "avatar_url": "https://avatars.githubusercontent.com/u/110495988?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Joshua-Mondie",
      "html_url": "https://github.com/Joshua-Mondie",
      "followers_url": "https://api.github.com/users/Joshua-Mondie/followers",
      "following_url": "https://api.github.com/users/Joshua-Mondie/following{/other_user}",
      "gists_url": "https://api.github.com/users/Joshua-Mondie/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Joshua-Mondie/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Joshua-Mondie/subscriptions",
      "organizations_url": "https://api.github.com/users/Joshua-Mondie/orgs",
      "repos_url": "https://api.github.com/users/Joshua-Mondie/repos",
      "events_url": "https://api.github.com/users/Joshua-Mondie/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Joshua-Mondie/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "victoriagreat",
      "id": 110530347,
      "node_id": "U_kgDOBpaPKw",
      "avatar_url": "https://avatars.githubusercontent.com/u/110530347?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/victoriagreat",
      "html_url": "https://github.com/victoriagreat",
      "followers_url": "https://api.github.com/users/victoriagreat/followers",
      "following_url": "https://api.github.com/users/victoriagreat/following{/other_user}",
      "gists_url": "https://api.github.com/users/victoriagreat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/victoriagreat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/victoriagreat/subscriptions",
      "organizations_url": "https://api.github.com/users/victoriagreat/orgs",
      "repos_url": "https://api.github.com/users/victoriagreat/repos",
      "events_url": "https://api.github.com/users/victoriagreat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/victoriagreat/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Uzochukwu001",
      "id": 112668327,
      "node_id": "U_kgDOBrcupw",
      "avatar_url": "https://avatars.githubusercontent.com/u/112668327?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Uzochukwu001",
      "html_url": "https://github.com/Uzochukwu001",
      "followers_url": "https://api.github.com/users/Uzochukwu001/followers",
      "following_url": "https://api.github.com/users/Uzochukwu001/following{/other_user}",
      "gists_url": "https://api.github.com/users/Uzochukwu001/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Uzochukwu001/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Uzochukwu001/subscriptions",
      "organizations_url": "https://api.github.com/users/Uzochukwu001/orgs",
      "repos_url": "https://api.github.com/users/Uzochukwu001/repos",
      "events_url": "https://api.github.com/users/Uzochukwu001/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Uzochukwu001/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "chinenyenwilo",
      "id": 114420346,
      "node_id": "U_kgDOBtHqeg",
      "avatar_url": "https://avatars.githubusercontent.com/u/114420346?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chinenyenwilo",
      "html_url": "https://github.com/chinenyenwilo",
      "followers_url": "https://api.github.com/users/chinenyenwilo/followers",
      "following_url": "https://api.github.com/users/chinenyenwilo/following{/other_user}",
      "gists_url": "https://api.github.com/users/chinenyenwilo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chinenyenwilo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chinenyenwilo/subscriptions",
      "organizations_url": "https://api.github.com/users/chinenyenwilo/orgs",
      "repos_url": "https://api.github.com/users/chinenyenwilo/repos",
      "events_url": "https://api.github.com/users/chinenyenwilo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chinenyenwilo/received_events",
      "type": "User",
      "site_admin": false
    }
  ]