export default {
    "login": "Developer-Kingz",
    "id": 109589113,
    "node_id": "U_kgDOBogyeQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/109589113?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Developer-Kingz",
    "html_url": "https://github.com/Developer-Kingz",
    "followers_url": "https://api.github.com/users/Developer-Kingz/followers",
    "following_url": "https://api.github.com/users/Developer-Kingz/following{/other_user}",
    "gists_url": "https://api.github.com/users/Developer-Kingz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Developer-Kingz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Developer-Kingz/subscriptions",
    "organizations_url": "https://api.github.com/users/Developer-Kingz/orgs",
    "repos_url": "https://api.github.com/users/Developer-Kingz/repos",
    "events_url": "https://api.github.com/users/Developer-Kingz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Developer-Kingz/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Kingsley Igbor",
    "company": "Skillup Africa",
    "blog": "",
    "location": "Abijo, Lagos, Nigeria",
    "email": null,
    "hireable": null,
    "bio": "Frontend Developer (talks: Javascript, React, HTML, CSS) ",
    "twitter_username": "DaKingzMan",
    "public_repos": 21,
    "public_gists": 0,
    "followers": 14,
    "following": 16,
    "created_at": "2022-07-19T09:42:52Z",
    "updated_at": "2022-12-19T11:14:08Z"
  }